### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ElephantRyan**
End of Sprint 1 Pull to Master -
App image files made
Initial Documentation added

### CODE REVIEW

**Comment by gamebofh** [comment]
Looks like a good start!

**Comment by gamebofh** [comment]
Let me know if that isn't what you needed.  :P

**Review by carlosfrancose — DISMISSED** [review]
Everything looks good. No compiler errors since there is nothing that needs to be compiled.

**Review by hcedill1 — COMMENTED** [review]
Looks good so far, having the environment setup.

**Comment by zmotcheck** [comment]
Merge this stuff

**Review by zmotcheck — APPROVED** [review]
Looks good to merge to master

**Review by hcedill1 — APPROVED** [review]
Looks great!!

**Review by carlosfrancose — APPROVED** [review]
Everything functions fine on my end, should merge.

**Pull request merged**
